apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: "mysql-config"
            - secretRef:
                name: "mysql-secret"
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: datskin.io/ogorodnikov-server
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: "mysql-config"
            - secretRef:
                name: "mysql-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
---
apiVersion: v1
kind: Secret
metadata:
  name: "mysql-secret"
data:
  MYSQL_USER: b3BlcmF0b3I=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "mysql-config"
data:
  MYSQL_HOST: "mysql-service:3306"
  MYSQL_DATABASE: "db"
  MYSQL_SKILLFACTORY_DATABASE_NAME: "reg1"

